import cx from "classnames";
import * as React from "react";

export type IconName =
  | "default"
  | "fonts"
  | "h1"
  | "h2"
  | "h3"
  | "file-arrow-down"
  | "file-music"
  | "file-play"
  | "file-text"
  | "outline-key"
  | "outline-cheveron-right"
  | "outline-cheveron-down"
  | "solid-check-circle"
  | "solid-star"
  | "cart-plus"
  | "bold"
  | "italic"
  | "underline"
  | "strikethrough"
  | "quote"
  | "unordered-list"
  | "ordered-list"
  | "code"
  | "horizontal-rule"
  | "undo"
  | "redo"
  | "link"
  | "upload-fill"
  | "media"
  | "paperclip"
  | "files-earmark"
  | "dropbox"
  | "card-text"
  | "file-text"
  | "folder-plus"
  | "input-cursor-text"
  | "outline-cheveron-left"
  | "grid"
  | "file-earmark-medical"
  | "outline-key"
  | "twitter"
  | "button"
  | "plus"
  | "chevron-right"
  | "chevron-left"
  | "chevron-down"
  | "arrow-right"
  | "arrow-left"
  | "close"
  | "menu"
  | "search"
  | "user"
  | "settings"
  | "home"
  | "dashboard"
  | "products"
  | "orders"
  | "analytics"
  | "customers"
  | "affiliates"
  | "help"
  | "logout"
  | "trash2"
  | "pencil"
  | "three-dots"
  | "box-arrow-in-right-fill";

type IconProps = {
  name: IconName;
} & React.JSX.IntrinsicElements["span"];
export const Icon = ({ name, className, ...props }: IconProps) => (
  <span className={cx("icon", `icon-${name}`, className)} {...props} />
);
