development:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

test:
  adapter: test

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
  url: <%= ENV.fetch("ANYCABLE_REDIS_URL") { "redis://#{ENV.fetch('REDIS_HOST', '127.0.0.1:6379')}/5" } %>
  channel_prefix: gumroad_production
