development: &development
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DATABASE_NAME", "gumroad_development") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  <% if ENV["DATABASE_SSL"] == "true" %>
  sslmode: require
  <% end %>
  variables:
    statement_timeout: <%= 5 * 60000 %> # 5 minutes

test:
  <<: *development
  database: <%= ENV.fetch("TEST_DATABASE_NAME", "gumroad_test") %>

staging: &staging
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DATABASE_NAME", "postgres") %>
  host: <%= ENV.fetch("DATABASE_HOST", "db.qewjnagvsbnwgamrrrwg.supabase.co") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
  timeout: 5000
  connect_timeout: 10
  sslmode: require
  variables:
    statement_timeout: <%= 5 * 60000 %> # 5 minutes

production:
  <<: *staging