uk:
  devise:
    confirmations:
      confirmed: "Ваш обліковий запис успішно підтверджено."
      send_instructions: "Протягом декількох хвилин ви отримаєте лист з інструкціями щодо підтвердження вашого облікового запису."
      send_paranoid_instructions: "Якщо ваша адреса e-mail є в нашій базі даних, протягом декількох хвилин ви отримаєте лист з інструкціями щодо підтвердження вашого облікового запису."
    failure:
      already_authenticated: "Ви вже увійшли до системи."
      inactive: "Ваш обліковий запис ще не активовано."
      invalid: "Неправильний email або пароль."
      locked: "Ваш обліковий запис заблоковано."
      last_attempt: "У вас залишилася остання спроба, перш ніж ваш обліковий запис буде заблоковано."
      not_found_in_database: "Неправильний email або пароль."
      timeout: "Ваш сеанс закінчився. Будь ласка, увійдіть знову, щоб продовжити."
      unauthenticated: "Вам необхідно увійти або зареєструватися, перш ніж продовжити."
      unconfirmed: "Ви повинні підтвердити свій обліковий запис, перш ніж продовжити."
    mailer:
      confirmation_instructions:
        subject: "Інструкції з підтвердження облікового запису"
      reset_password_instructions:
        subject: "Інструкції зі скидання пароля"
      unlock_instructions:
        subject: "Інструкції з розблокування"
      email_changed:
        subject: "Попередження безпеки: вашу електронну адресу на Gumroad змінюють"
      password_change:
        subject: "Пароль змінено"
    omniauth_callbacks:
      failure: "Не вдалося автентифікувати вас з %{kind} через помилку: \"%{reason}\"."
      success: "Успішна автентифікація з облікового запису %{kind}."
    passwords:
      no_token: "Ви не можете отримати доступ до цієї сторінки без переходу за посиланням у листі для скидання пароля. Якщо ви перейшли за таким посиланням, переконайтеся, що ви використали повний URL."
      send_instructions: "Протягом декількох хвилин ви отримаєте лист з інструкціями щодо відновлення вашого пароля."
      send_paranoid_instructions: "Якщо ваша адреса e-mail є в нашій базі даних, протягом декількох хвилин ви отримаєте лист з інструкціями щодо відновлення вашого пароля."
      updated: "Ваш пароль успішно змінено. Ви увійшли до системи."
      updated_not_active: "Ваш пароль успішно змінено."
    registrations:
      destroyed: "До побачення! Ваш обліковий запис успішно видалено. Сподіваємося скоро побачити вас знову."
      signed_up: "Ласкаво просимо! Ви успішно зареєструвалися."
      signed_up_but_inactive: "Ви успішно зареєструвалися. Однак ми не змогли увійти, оскільки ваш обліковий запис ще не активовано."
      signed_up_but_locked: "Ви успішно зареєструвалися. Однак ми не змогли увійти, оскільки ваш обліковий запис заблоковано."
      signed_up_but_unconfirmed: "Лист з посиланням для підтвердження було надіслано на вашу адресу e-mail. Будь ласка, перейдіть за посиланням, щоб активувати ваш обліковий запис."
      update_needs_confirmation: "Ви успішно оновили свій обліковий запис, але нам потрібно перевірити вашу нову адресу e-mail. Будь ласка, перевірте свою пошту і перейдіть за посиланням для підтвердження, щоб завершити зміну адреси."
      updated: "Ваш обліковий запис успішно оновлено."
      updated_but_not_signed_in: "Ваш обліковий запис успішно оновлено, але оскільки ваш пароль було змінено, вам потрібно увійти знову."
    sessions:
      signed_in: "Вхід до системи успішно виконано."
      signed_out: "Вихід із системи успішно виконано."
      already_signed_out: "Вихід із системи успішно виконано."
    unlocks:
      send_instructions: "Протягом декількох хвилин ви отримаєте лист з інструкціями щодо розблокування вашого облікового запису."
      send_paranoid_instructions: "Якщо ваш обліковий запис існує, протягом декількох хвилин ви отримаєте лист з інструкціями щодо його розблокування."
      unlocked: "Ваш обліковий запис успішно розблоковано. Будь ласка, увійдіть, щоб продовжити."
  errors:
    messages:
      already_confirmed: "вже було підтверджено, будь ласка, спробуйте увійти"
      confirmation_period_expired: "потрібно було підтвердити протягом %{period}, будь ласка, запросіть новий"
      expired: "закінчився, будь ласка, запросіть новий"
      not_found: "не знайдено"
      not_locked: "не було заблоковано"
      not_saved:
        one: "1 помилка не дозволила зберегти цей %{resource}:"
        other: "%{count} помилок не дозволили зберегти цей %{resource}:"
      pwned_password: "цей пароль раніше був скомпрометований (за даними haveibeenpwned.com) і не повинен використовуватись. Будь ласка, оберіть складніший варіант."