development:
  clients:
    default:
      hosts:
        - <%= ENV.fetch("MONGO_DATABASE_URL", "localhost:27017") %>
      database: <%= ENV.fetch("MONGO_DATABASE_NAME", "gumroad_development") %>
  options:
    use_utc: true
    raise_not_found_error: false

test:
  clients:
    default:
      hosts:
        - <%= ENV.fetch("MONGO_DATABASE_URL", "localhost:27017") %>
      database: <%= ENV.fetch("MONGO_DATABASE_NAME", "gumroad_test") %>
  options:
    use_utc: true
    raise_not_found_error: false

staging:
  clients:
    default:
      hosts:
        - <%= ENV.fetch("MONGO_DATABASE_URL", "localhost:27017") %>
      database: <%= ENV.fetch("MONGO_DATABASE_NAME", "gumroad_staging") %>
      options:
        user: <%= ENV.fetch("MONGO_DATABASE_USERNAME", "") %>
        password: <%= ENV.fetch("MONGO_DATABASE_PASSWORD", "") %>
        replica_set: <%= ENV["MONGO_REPLICA_SET"] %>
  options:
    use_utc: true
    raise_not_found_error: false

production:
  clients:
    default:
      hosts:
        - <%= ENV.fetch("MONGO_DATABASE_URL", "localhost:27017") %>
      database: <%= ENV.fetch("MONGO_DATABASE_NAME", "gumroad_production") %>
      options:
        user: <%= ENV.fetch("MONGO_DATABASE_USERNAME", "") %>
        password: <%= ENV.fetch("MONGO_DATABASE_PASSWORD", "") %>
        replica_set: <%= ENV["MONGO_REPLICA_SET"] %>
  options:
    use_utc: true
    raise_not_found_error: false
